### ISSUE TITLE
How can i use python selenium to automate my task with this?

### ISSUE THREAD

**Issue by readthecodes** [CheshireCaat/selenium-with-fingerprints#10]
I'm familiar with python, and not familiar with JS, so i want to use python control opened Chrome to do automate task. 

step 1: use selenium-with-fingerprints to start different fingerprint browser.
step 2: use python selenium to control the browser started from step 1, do automatic task with python code instead of JS code.

How can I achieve this?

**Comment by sergerdn** [comment]
I had the same problem about a month ago, and I made the decision to improve my JavaScript/TypeScript skills instead of work with Python.

At the moment, TypeScript is very similar to Python or Golang in terms of typing, clean interfaces from out of box , and other features.

Have you looked https://github.com/CheshireCaat/selenium-with-fingerprints/issues/5?

**Comment by CheshireCaat** [comment]
At the moment there is no version for **python**, you can implement interaction with **JS** yourself, but at your own risk.
